{{- if .Values.externalAccess.enabled }}
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ template "pravega.fullname" . }}-{{ .Release.Namespace }}
  labels:
{{ include "pravega.commonLabels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "pravega.fullname" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ template "pravega.fullname" . }}-{{ .Release.Namespace }}
  apiGroup: rbac.authorization.k8s.io
{{- end }}
